# Generated by Django 5.0.4 on 2024-04-30 06:43

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaymessage',
            name='month_of_birth',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='activity_unit',
            field=models.CharField(max_length=100, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_number',
            field=models.CharField(max_length=12, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='specilization',
            field=models.CharField(max_length=100, verbose_name='تخصص'),
        ),
    ]
