# Generated by Django 5.0.4 on 2024-04-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_app', '0002_alter_birthdaymessage_month_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaymessage',
            name='month_of_birth',
            field=models.IntegerField(),
        ),
    ]
