# Generated by Django 5.0.4 on 2024-04-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_app', '0003_alter_birthdaymessage_month_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ad_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد میلادی'),
        ),
    ]
